export const BUSCARPORNOMBRE = 'BUSCARPORNOMBRE';





//!LAS ACTIOS TYPES NOS SIRVEN PARA IR AGREGANDO LOS NOMBRES DE LAS ACCIONES Y DESPUES ENVIARSELAS AL ARCHIVO ACTIOS PARA LUEGO UTILZIAR EN EL REDUCER
//! POR FAVOR TODAS LAS ACTIONS AGREGARLAS DE ESTE LADO PRIMERO Y LUEGO PASARLAS AL actions.js